name: ci

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MVN: mvn --show-version --batch-mode
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: cache ~/.m2
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2  
      - name: mvn clean compile
        run: $MVN clean compile
      - name: mvn test
        run: $MVN test
      - name: mvn package -DskipTests
        run: $MVN package -DskipTests
      - name: mvn package -DskipTests -Pnative
        run: $MVN package -DskipTests -Pnative
      - name: mvn verify -Pnative  
        run: $MVN verify -Pnative
